spring:
    application:
        name: IggyTheBlog
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/personelblog}
        username: ${SPRING_DATASOURCE_USERNAME:personelblog}
        password: ${SPRING_DATASOURCE_PASSWORD:personelblog}
        driver-class-name: org.postgresql.Driver
        hikari:
            schema: myblog
    flyway:
        baseline-on-migrate: true
        fail-on-missing-locations: true
        schemas: ${spring.datasource.hikari.schema}
    jpa:
        hibernate:
             ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                default_schema: myblog
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    jackson:
        serialization:
            INDENT_OUTPUT: true

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

server:
    port: 8080
    shutdown: graceful

blog:
    myblog:
        api:
            base-path: /IggyTheBlog/1

