spring:
    application:
        name: IggyTheBlog
    datasource:
        url: ""
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
            schema:
    flyway:
        baseline-on-migrate: true
        fail-on-missing-locations: true
        schema: ${spring.datasource.hikari.schema}

server:
    port: 9090
    shutdown: graceful

blog:
    myblog:
        api:
            base-path: /IggyTheBlog/1

